### ISSUE TITLE
Php 8 support

### ISSUE THREAD

**Issue by quarente** [bpocallaghan/add-to-homescreen#6]
bpocallaghan/add-to-homescreen 0.3 requires php ^7.2.5 which does not match your installed version 8.1.5.

**Comment by bpocallaghan** [comment]
Hi @quarente 
Thanks for raising the issue.
I have added a tag 0.4 and 0.5 for PHP 8 and PHP 8.1.

Please give it another try and let me know if its working for you now.

Thanks
